name: aplicacion_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.10
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.1.1
  xml: ^6.5.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  carousel_slider: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/Diseño/ 
    - assets/Acuña/ 
    - assets/Rutas/
    - assets/Avisos/
    - assets/Eventos/
    - assets/Cine/
    - assets/Espacios/
    - assets/Turismo/
    - assets/Mascotas/
    - assets/Directorio/
    - assets/Bares/